/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTripsIndexRouteImport } from './routes/_auth.trips.index'
import { Route as AuthTripsNewRouteImport } from './routes/_auth.trips.new'
import { Route as AuthTripsTripIdRouteImport } from './routes/_auth.trips.$tripId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTripsIndexRoute = AuthTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTripsNewRoute = AuthTripsNewRouteImport.update({
  id: '/trips/new',
  path: '/trips/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTripsTripIdRoute = AuthTripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/trips/$tripId': typeof AuthTripsTripIdRoute
  '/trips/new': typeof AuthTripsNewRoute
  '/trips': typeof AuthTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/trips/$tripId': typeof AuthTripsTripIdRoute
  '/trips/new': typeof AuthTripsNewRoute
  '/trips': typeof AuthTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/trips/$tripId': typeof AuthTripsTripIdRoute
  '/_auth/trips/new': typeof AuthTripsNewRoute
  '/_auth/trips/': typeof AuthTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/trips/$tripId'
    | '/trips/new'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/trips/$tripId' | '/trips/new' | '/trips'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/trips/$tripId'
    | '/_auth/trips/new'
    | '/_auth/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/trips/': {
      id: '/_auth/trips/'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthTripsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trips/new': {
      id: '/_auth/trips/new'
      path: '/trips/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AuthTripsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/trips/$tripId': {
      id: '/_auth/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AuthTripsTripIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthTripsTripIdRoute: typeof AuthTripsTripIdRoute
  AuthTripsNewRoute: typeof AuthTripsNewRoute
  AuthTripsIndexRoute: typeof AuthTripsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthTripsTripIdRoute: AuthTripsTripIdRoute,
  AuthTripsNewRoute: AuthTripsNewRoute,
  AuthTripsIndexRoute: AuthTripsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
